pipeline {
    agent any

    parameters {
        choice(choices: ['option', 'kubectl apply', 'kubectl delete'], name: 'DEPLOY_COMMAND', description: '배포 타입 선택')
        choice(choices: ['option', 'club-vs'], name: 'TARGET_VIRTUAL_SERVICE', description: 'Virtual Service 대상 선택')
    }

    environment {
        INSTALL_PATH = 'virtual-service'
    }

    stages {
        stage('deploy virtual service') {
            steps {
                script{
                    sh "${params.DEPLOY_COMMAND} -f ${INSTALL_PATH}/${params.TARGET_VIRTUAL_SERVICE}.yaml"
                }
            }
        }
    }
}