pipeline {
    agent any

    parameters {
        choice(choices: ['option', 'kubectl apply', 'kubectl delete'], name: 'DEPLOY_COMMAND', description: '배포 타입 선택')
        choice(choices: ['option', 'clubVs', 'scheduleVs', 'postingVs', 'memberVs', 'accountVs', 'notificationVs'], name: 'TARGET_VIRTUAL_SERVICE', description: 'Virtual Service 대상 선택')
    }

    environment {
        INSTALL_PATH = 'networking/virtualService'
        NAME_SPACE = 'moremore'
    }

    stages {
        stage('deploy virtual service') {
            steps {
                script{
                    sh "${params.DEPLOY_COMMAND} -f ${INSTALL_PATH}/${params.TARGET_VIRTUAL_SERVICE}.yaml -n ${NAME_SPACE}"
                }
            }
        }
    }
}