apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: member-vs
spec:
  hosts:
  - "*"
  gateways:
  - moremore-gateway
  http:
  - match:
    - uri:
        prefix: /api/member
    route:
    - destination:
        host: member-service
        port:
          number: 80
