apiVersion: v1
kind: Service
metadata:
  namespace: moremore
  name: club-service
  labels:
    part-of: moremore
    name: club-service
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: moremore
    name: club-service
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 31081
  type: NodePort
