apiVersion: v1
kind: Service
metadata:
  name: {{ include "posting-service.fullname" . }}
  labels:
    {{- include "posting-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }} 
      nodePort: {{ .Values.service.nodePort }}
      name: {{ .Values.service.portName }}
  selector:
    {{- include "posting-service.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "posting-service.fullname" . }}-preview
  labels:
    {{- include "posting-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }} 
      nodePort: {{ .Values.service.nodePortPreview }}
      name: {{ .Values.service.portName }}-preview
  selector:
    {{- include "posting-service.selectorLabels" . | nindent 4 }}


