apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster-1
spec:
  storageClassName: "redis-cluster-storage"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /home/ubuntu/redis-pv/redis-pv-1

  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster-2
spec:
  storageClassName: "redis-cluster-storage"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /home/ubuntu/redis-pv/redis-pv-2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster-3
spec:
  storageClassName: "redis-cluster-storage"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /home/ubuntu/redis-pv/redis-pv-3


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster-4
spec:
  storageClassName: "redis-cluster-storage"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /home/ubuntu/redis-pv/redis-pv-4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster-5
spec:
  storageClassName: "redis-cluster-storage"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /home/ubuntu/redis-pv/redis-pv-5

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster-6
spec:
  storageClassName: "redis-cluster-storage"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /home/ubuntu/redis-pv/redis-pv-6
