apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
spec:
  selector:
    matchLabels:
      istio: gateway
  jwtRules:
  - issuer: "moremore"
    jwksUri: "http://member-service.moremore/.moremore/jwks.json"
    fromHeaders:
    - name: Authorization
      prefix: "Bearer "
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-policy
spec:
  selector:
    matchLabels:
      istio: gateway
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/api/club"]