apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "club-service.fullname" . }}
  labels:
    {{- include "club-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    blueGreen:
      activeService: {{ include "club-service.fullname" . }}
      previewService: {{ include "club-service.fullname" . }}-preview
      autoPromotionEnabled: true
  selector:
    matchLabels:
      {{- include "club-service.selectorLabels" . | nindent 6 }}
      {{- include "club-service.podlabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "club-service.labels" . | nindent 8 }}
        {{- include "club-service.podlabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }} 
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
