pipeline {
    agent any

    parameters {
        choice(choices: ['option', 'helm_upgrade', 'helm_uninstall'], name: 'DEPLOY_TYPE', description: '배포 타입 선택')
        choice(choices: ['option', 'redis-cluster'], name: 'TARGET_REDIS', description: 'Redis 대상 선택')
    }

    environment {
        INSTALL_PATH = 'redis'
        NAME_SPACE = 'moremore'
    }

    stages {
        stage('deploy redis-cluster') {
            steps {
                script{
                    if (params.DEPLOY_TYPE == "helm_upgrade") {
                        HELM_DEPLOY_COMMAND =  "helm upgrade ${params.TARGET_REDIS} ./${INSTALL_PATH}/helm/${params.TARGET_REDIS} " +
                            " -f ./${INSTALL_PATH}/helm/${params.TARGET_REDIS}/values-dev.yaml" +
                            " -n ${NAME_SPACE} --install " + 
                            " --wait --timeout=10m "   // 최대 10분으로 설정
                           sh "eval ${HELM_DEPLOY_COMMAND}"                 
                    } else if (params.DEPLOY_TYPE == "helm_uninstall") {
                        sh "helm uninstall ${params.TARGET_REDIS} -n ${NAME_SPACE} "
                    } else {
                        echo "skip deploy"
                    }
                }
            }
        }
    }
}